server:
  port: 9870

spring:
  profiles:
    active: dev
  application:
    name: ChatCove
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

# mybaits-plus配置
mybatis-plus:
  # 搜索指定包别名
  typeAliasesPackage: com.ambisiss.**.entity
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/*Mapper.xml
  # 配置控制台打印完整带参数SQL语句
  configuration:
    logImpl: org.apache.ibatis.logging.stdout.StdOutImpl

# PageHelper分页插件
pagehelper:
  #分页插件会自动检测当前的数据库链接，自动选择合适的分页方式。
  helperDialect: mysql
  #分页合理化参数，默认值为 false 。当该参数设置为 true 时， pageNum<=0 时会查询第一页， pageNum>pages （超过总数时），会查询最后一页。
  reasonable: true
  #支持通过Mapper接口参数传递page参数,默认值为falset
  supportMethodsArguments: true
  #默认值为 false ，当该参数设置为 true 时，如果 pageSize=0 或者 RowBounds.limit =0 就会查询出全部的结果（相当于没有执行分页查询，但是返回结果仍然是 Page 类型）
  params: count=countSql
  #默认值为 false ，当该参数设置为 true 时，如果 pageSize=0 或者 RowBounds.limit =0 就会查询出全部的结果（相当于没有执行分页查询，但是返回结果仍然是 Page 类型）
  pageSizeZero: true

jwt:
  # header:凭证(校验的变量名)
  header: Authorization
  # 有效期1天(单位:s)
  expire: 5184000
  # secret: 秘钥(普通字符串) 不能太短，太短可能会导致报错
  secret: T1Bm7sLdHfRy6V8gjK4a
  # 签发者
  issuer: admin

